import Head from "next/head";
import axios from "axios";

import { countries } from "@/data";

export default function Home({ countries, primaryContact }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hi</h1>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let portalUser = {};
  let otherUsers = [];

  async function fetchData() {
    try {
      const response = await axios.get(process.env.ACCESSTOKEN_URL);
      const userFound = await axios.get(
        `https://www.zohoapis.com/crm/v3/Contacts/4295937000002194589`,
        {
          headers: {
            Authorization: response.data.access_token,
          },
        }
      );
      console.log("Access Token ", response.data.access_token);

      portalUser = userFound.data.data[0];
      console.log(portalUser);
    } catch (error) {
      console.log({ test: error });
    }
  }

  await fetchData();
  return {
    props: {
      countries: countries || [],
      primaryContact: portalUser || {},
    }, // will be passed to the page component as props
  };
}
