import Head from "next/head";

import { Box, Typography } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Travela</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <Box
          sx={{
            width: "100%",
            height: {
              lg: "82vh",
              md: "82vh",
              sm: "100%",
              xs: "100%",
            },
            backgroundColor: "white",
            display: "flex",
            flexDirection: {
              lg: "row",
              md: "row",
              sm: "column",
              xs: "column",
            },
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Typography>Go to the link provided by CRM.</Typography>
        </Box>
      </main>
    </>
  );
}
